# -*- coding: utf-8 -*-
"""r2dplus1dsoccernet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MGotuzw4kxrM8yOjJkS9GFJkKVnLNy1U
"""

# CELL 1 — Mount Drive + paths (persistent)
from google.colab import drive
drive.mount("/content/drive")

import os, sys

PROJECT_DIR = "/content/drive/MyDrive/as_soccernet"
DATA_DIR    = f"{PROJECT_DIR}/data"
WORK_DIR    = f"{PROJECT_DIR}/work"
CKPT_DIR    = f"{PROJECT_DIR}/checkpoints"
LOG_DIR     = f"{PROJECT_DIR}/logs"

for d in [PROJECT_DIR, DATA_DIR, WORK_DIR, CKPT_DIR, LOG_DIR]:
    os.makedirs(d, exist_ok=True)

print("PROJECT_DIR:", PROJECT_DIR)
print("DATA_DIR   :", DATA_DIR)
print("CKPT_DIR   :", CKPT_DIR)

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# # CELL 2
# set -e
# REPO_DIR="/content/drive/MyDrive/soccernet_r2plus1d/repo"
# YOUR_REPO_URL="https://github.com/YOUR_USER/YOUR_REPO.git"
# 
# if [ "$YOUR_REPO_URL" != "https://github.com/YOUR_USER/YOUR_REPO.git" ]; then
#   if [ ! -d "$REPO_DIR/.git" ]; then
#     git clone "$YOUR_REPO_URL" "$REPO_DIR"
#   else
#     cd "$REPO_DIR"
#     git pull
#   fi
#   echo "Repo at: $REPO_DIR"
# else
#   echo "Skipped: set YOUR_REPO_URL in this cell if you have a repo."
# fi
#

# CELL 3 — Add repo to PYTHONPATH (optional)
REPO_DIR = "/content/drive/MyDrive/soccernet_r2plus1d/repo"
if os.path.isdir(REPO_DIR):
    sys.path.append(REPO_DIR)
    print("Added to path:", REPO_DIR)

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# # CELL 4 — Install deps
# pip -q install SoccerNet opencv-python pytorchvideo
#

# CELL 5 — GPU check
import torch
print("Torch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
if torch.cuda.is_available():
    print("GPU:", torch.cuda.get_device_name(0))

# Commented out IPython magic to ensure Python compatibility.
# %%bash
# pip -q install SoccerNet

# Download dataset
import os, sys
from SoccerNet.Downloader import SoccerNetDownloader



dl = SoccerNetDownloader(LocalDirectory=DATA_DIR)

# NDA video password
dl.password = "s0cc3rn3t"

# Download 224p MKV videos (both halves)

dl.downloadGames(files=["Labels-v2.json"], split=["train","valid","test"])

print("Done downloading ")

# CELL 6 — Build manifest with positives (goal) + negatives (background), split-aware + half-aware

import os, glob, json, random
import pandas as pd
import cv2
from SoccerNet.utils import getListGames

MANIFEST_PATH = f"{WORK_DIR}/manifest_goal_vs_bg.csv"

# -------------------------
# Config
# -------------------------
NEG_PER_POS = 5      # negatives per goal (start with 3–10)
MIN_GAP_SEC = 10.0   # negatives must be at least this many seconds away from ANY event time
CLIP_SEC = 4.0       # used to avoid sampling too close to edges
SEED = 42
random.seed(SEED)

# -------------------------
# Split lookup (source of truth)
# -------------------------
SPLITS = {
    "train": set(getListGames("train")),
    "valid": set(getListGames("valid")),
    "test":  set(getListGames("test")),
}
def get_split(rel_game):
    for s, games in SPLITS.items():
        if rel_game in games:
            return s
    return "unknown"

# -------------------------
# Helpers
# -------------------------
def find_jsons(root):
    return glob.glob(os.path.join(root, "**", "*.json"), recursive=True)

def safe_get_event_list(obj):
    if isinstance(obj, dict):
        for k in ["annotations", "Annotations", "Actions", "events", "Labels"]:
            if k in obj and isinstance(obj[k], list):
                return obj[k]
    return []

def event_label(ev):
    for k in ["label", "event", "type", "action", "class"]:
        if k in ev and isinstance(ev[k], str):
            return ev[k]
    if "event" in ev and isinstance(ev["event"], dict) and isinstance(ev["event"].get("label"), str):
        return ev["event"]["label"]
    return None

def parse_game_time(game_time: str):
    # "1 - 12:34"
    if not isinstance(game_time, str) or "-" not in game_time:
        return None, None
    half_str, mmss = game_time.split("-", 1)
    half_str, mmss = half_str.strip(), mmss.strip()
    try:
        half = int(half_str)
        mm, ss = mmss.split(":")
        tsec = int(mm) * 60 + int(ss)
        return half, float(tsec)
    except Exception:
        return None, None

def video_duration_sec(video_path: str):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        return None
    fps = cap.get(cv2.CAP_PROP_FPS) or 25.0
    n = cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0
    cap.release()
    if n <= 1:
        return None
    return float(n / fps)

def sample_background_times(duration, forbidden_times, n_samples, min_gap=10.0):
    """
    duration: seconds in this half-video
    forbidden_times: list of event times (seconds) in this half
    returns list of sampled background center_sec
    """
    if duration is None or duration <= (CLIP_SEC + 1):
        return []
    lo = CLIP_SEC/2
    hi = duration - CLIP_SEC/2
    if hi <= lo:
        return []

    out = []
    tries = 0
    max_tries = 5000

    forbidden_times = list(forbidden_times)

    while len(out) < n_samples and tries < max_tries:
        tries += 1
        t = random.uniform(lo, hi)
        # far from any event
        if all(abs(t - e) >= min_gap for e in forbidden_times):
            out.append(t)
            forbidden_times.append(t)  # keep negatives spread out too (optional)
    return out

# -------------------------
# Find root
# -------------------------
possible_roots = [os.path.join(DATA_DIR, "SoccerNet"), DATA_DIR]
root = next((p for p in possible_roots if os.path.isdir(p)), None)
print("Using root:", root)

if os.path.exists(MANIFEST_PATH):
    print("Manifest already exists:", MANIFEST_PATH)
else:
    rows = []
    jsons = find_jsons(root) if root else []
    print("Found JSON files:", len(jsons))

    for jp in jsons:
        match_dir = os.path.dirname(jp)

        v1 = os.path.join(match_dir, "1_224p.mkv")
        v2 = os.path.join(match_dir, "2_224p.mkv")
        if not (os.path.exists(v1) and os.path.exists(v2)):
            continue

        rel_game = os.path.relpath(match_dir, start=DATA_DIR)
        split = get_split(rel_game)
        if split == "unknown":
            continue

        try:
            with open(jp, "r") as f:
                obj = json.load(f)
        except Exception:
            continue

        events = safe_get_event_list(obj)
        if not events:
            continue

        # Collect all event times per half (for "stay away from any event" negatives)
        all_times = {1: [], 2: []}
        goal_times = {1: [], 2: []}

        for ev in events:
            raw = event_label(ev)
            if raw is None:
                continue
            half, tsec = parse_game_time(ev.get("gameTime", ""))
            if half not in (1, 2) or tsec is None:
                continue

            all_times[half].append(tsec)

            if raw.strip().lower() == "goal":
                goal_times[half].append(tsec)

        # Add goal positives + background negatives per half
        for half in (1, 2):
            video_path = v1 if half == 1 else v2
            dur = video_duration_sec(video_path)
            if dur is None:
                continue

            # positives
            for tsec in goal_times[half]:
                rows.append({
                    "split": split,
                    "rel_game": rel_game,
                    "video_path": video_path,
                    "half": half,
                    "center_sec": float(tsec),
                    "label": "goal"
                })

            # negatives: NEG_PER_POS per positive in this half
            n_neg = NEG_PER_POS * len(goal_times[half])
            if n_neg > 0:
                neg_times = sample_background_times(
                    duration=dur,
                    forbidden_times=all_times[half],
                    n_samples=n_neg,
                    min_gap=MIN_GAP_SEC
                )
                for t in neg_times:
                    rows.append({
                        "split": split,
                        "rel_game": rel_game,
                        "video_path": video_path,
                        "half": half,
                        "center_sec": float(t),
                        "label": "background"
                    })

    df = pd.DataFrame(rows).drop_duplicates()
    print("Rows:", len(df))
    if len(df) == 0:
        raise RuntimeError("Manifest is empty. Check DATA_DIR/JSON structure or whether goal labels exist.")

    print("\nLabel counts:\n", df["label"].value_counts())
    print("\nSplit counts:\n", df["split"].value_counts())

    df.to_csv(MANIFEST_PATH, index=False)
    print("Wrote:", MANIFEST_PATH)
    display(df.head())

# CELL — Build TEST manifest with positives (goal) + negatives (background)

import os, glob, json, random
import pandas as pd
import cv2
from SoccerNet.utils import getListGames

TEST_MANIFEST_PATH = f"{WORK_DIR}/manifest_test_goal_vs_bg.csv"

NEG_PER_POS = 5
MIN_GAP_SEC = 10.0
CLIP_SEC = 4.0
SEED = 42
random.seed(SEED)

SPLITS = {
    "train": set(getListGames("train")),
    "valid": set(getListGames("valid")),
    "test":  set(getListGames("test")),
}

def get_split(rel_game):
    for s, games in SPLITS.items():
        if rel_game in games:
            return s
    return "unknown"

def find_jsons(root):
    return glob.glob(os.path.join(root, "**", "*.json"), recursive=True)

def safe_get_event_list(obj):
    if isinstance(obj, dict):
        for k in ["annotations", "Annotations", "Actions", "events", "Labels"]:
            if k in obj and isinstance(obj[k], list):
                return obj[k]
    return []

def event_label(ev):
    for k in ["label", "event", "type", "action", "class"]:
        if k in ev and isinstance(ev[k], str):
            return ev[k]
    if "event" in ev and isinstance(ev["event"], dict) and isinstance(ev["event"].get("label"), str):
        return ev["event"]["label"]
    return None

def parse_game_time(game_time: str):
    if not isinstance(game_time, str) or "-" not in game_time:
        return None, None
    half_str, mmss = game_time.split("-", 1)
    half_str, mmss = half_str.strip(), mmss.strip()
    try:
        half = int(half_str)
        mm, ss = mmss.split(":")
        tsec = int(mm) * 60 + int(ss)
        return half, float(tsec)
    except Exception:
        return None, None

def video_duration_sec(video_path: str):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        return None
    fps = cap.get(cv2.CAP_PROP_FPS) or 25.0
    n = cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0
    cap.release()
    if n <= 1:
        return None
    return float(n / fps)

def sample_background_times(duration, forbidden_times, n_samples, min_gap=10.0):
    if duration is None or duration <= (CLIP_SEC + 1):
        return []
    lo = CLIP_SEC / 2
    hi = duration - CLIP_SEC / 2
    if hi <= lo:
        return []

    out = []
    tries, max_tries = 0, 5000
    forbidden_times = list(forbidden_times)

    while len(out) < n_samples and tries < max_tries:
        tries += 1
        t = random.uniform(lo, hi)
        if all(abs(t - e) >= min_gap for e in forbidden_times):
            out.append(t)
            forbidden_times.append(t)  # keep negatives spread out too
    return out

# ---- Root detection (same as yours) ----
possible_roots = [os.path.join(DATA_DIR, "SoccerNet"), DATA_DIR]
root = next((p for p in possible_roots if os.path.isdir(p)), None)
print("Using root:", root)

if root is None:
    raise RuntimeError("Could not find DATA_DIR/SoccerNet root.")

rows = []
jsons = find_jsons(root)
print("Found JSON files:", len(jsons))

for jp in jsons:
    match_dir = os.path.dirname(jp)

    v1 = os.path.join(match_dir, "1_224p.mkv")
    v2 = os.path.join(match_dir, "2_224p.mkv")
    if not (os.path.exists(v1) and os.path.exists(v2)):
        continue

    # IMPORTANT: use root here for split matching
    rel_game = os.path.relpath(match_dir, start=root)
    split = get_split(rel_game)

    # we only want TEST
    if split != "test":
        continue

    try:
        with open(jp, "r") as f:
            obj = json.load(f)
    except Exception:
        continue

    events = safe_get_event_list(obj)
    if not events:
        continue

    all_times = {1: [], 2: []}
    goal_times = {1: [], 2: []}

    for ev in events:
        raw = event_label(ev)
        if raw is None:
            continue
        half, tsec = parse_game_time(ev.get("gameTime", ""))
        if half not in (1, 2) or tsec is None:
            continue

        all_times[half].append(tsec)
        if raw.strip().lower() == "goal":
            goal_times[half].append(tsec)

    for half in (1, 2):
        video_path = v1 if half == 1 else v2
        dur = video_duration_sec(video_path)
        if dur is None:
            continue

        # positives
        for tsec in goal_times[half]:
            rows.append({
                "split": "test",
                "rel_game": rel_game,
                "video_path": video_path,
                "half": half,
                "center_sec": float(tsec),
                "label": "goal",
            })

        # negatives (NEG_PER_POS per goal)
        n_neg = NEG_PER_POS * len(goal_times[half])
        if n_neg > 0:
            neg_times = sample_background_times(
                duration=dur,
                forbidden_times=all_times[half],
                n_samples=n_neg,
                min_gap=MIN_GAP_SEC
            )
            for t in neg_times:
                rows.append({
                    "split": "test",
                    "rel_game": rel_game,
                    "video_path": video_path,
                    "half": half,
                    "center_sec": float(t),
                    "label": "background",
                })

df_test = pd.DataFrame(rows).drop_duplicates()
print("Rows:", len(df_test))
if len(df_test) == 0:
    raise RuntimeError("Test manifest is empty. (Likely: test has no annotations JSONs.)")

print("\nLabel counts:\n", df_test["label"].value_counts())
df_test.to_csv(TEST_MANIFEST_PATH, index=False)
print("Wrote:", TEST_MANIFEST_PATH)
display(df_test.head())

# CELL 7 — Clip loader + Dataset (train + valid splits, on-the-fly clips)

import cv2
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import os

# -------------------------
# Load manifest + splits
# -------------------------

MANIFEST_PATH = f"{WORK_DIR}/manifest_goal_vs_bg.csv"
df_all = pd.read_csv(MANIFEST_PATH)

df_train = df_all[df_all["split"] == "train"].reset_index(drop=True)
df_valid = df_all[df_all["split"] == "valid"].reset_index(drop=True)

print("train rows:", len(df_train))
print("valid rows:", len(df_valid))

# -------------------------
# Labels (from TRAIN only)
# -------------------------
labels = sorted(df_train["label"].unique().tolist())
label2id = {l: i for i, l in enumerate(labels)}
num_classes = len(labels)

print("labels:", labels)
print("num_classes:", num_classes)

# -------------------------
# Clip extraction
# -------------------------
def extract_clip_cv2(
    video_path,
    center_sec,
    clip_sec=4.0,
    num_frames=16,
    size=112,
):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise RuntimeError(f"Could not open video: {video_path}")

    fps = cap.get(cv2.CAP_PROP_FPS) or 25.0
    start_sec = max(0.0, center_sec - clip_sec / 2)
    start_frame = int(start_sec * fps)

    frames = []
    step = int(max(1, (clip_sec * fps) / num_frames))

    for i in range(num_frames):
        cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame + i * step)
        ok, frame = cap.read()
        if not ok:
            break
        frame = cv2.resize(frame, (size, size), interpolation=cv2.INTER_AREA)
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        frames.append(frame)

    cap.release()

    if len(frames) == 0:
        raise RuntimeError(f"No frames read from: {video_path}")

    # pad if video ended early
    while len(frames) < num_frames:
        frames.append(frames[-1].copy())

    arr = np.stack(frames, axis=0).astype(np.float32) / 255.0  # (T,H,W,C)
    arr = np.transpose(arr, (3, 0, 1, 2))  # (C,T,H,W)
    return torch.from_numpy(arr)

# -------------------------
# Dataset
# -------------------------
class SoccerNetClipDataset(Dataset):
    def __init__(self, df, label2id, clip_sec=4.0, num_frames=16, size=112):
        self.df = df.reset_index(drop=True)
        self.label2id = label2id
        self.clip_sec = clip_sec
        self.num_frames = num_frames
        self.size = size

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        r = self.df.iloc[idx]
        x = extract_clip_cv2(
            r.video_path,
            r.center_sec,
            self.clip_sec,
            self.num_frames,
            self.size,
        )
        y = self.label2id[r.label]
        return x, torch.tensor(y, dtype=torch.long)

# -------------------------
# DataLoaders
# -------------------------
train_ds = SoccerNetClipDataset(
    df_train,
    label2id,
    clip_sec=4.0,
    num_frames=16,
    size=112,
)

val_ds = SoccerNetClipDataset(
    df_valid,
    label2id,
    clip_sec=4.0,
    num_frames=16,
    size=112,
)

train_loader = DataLoader(
    train_ds,
    batch_size=6,
    shuffle=True,
    num_workers=2,
    pin_memory=True,
)

val_loader = DataLoader(
    val_ds,
    batch_size=6,
    shuffle=False,
    num_workers=2,
    pin_memory=True,
)

print("ready")

# Loader for test

# CELL 7 — Clip loader + Dataset (TEST only, on-the-fly clips)

import cv2
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import os

# -------------------------
# Load TEST manifest
# -------------------------
TEST_MANIFEST_PATH = f"{WORK_DIR}/manifest_test_goal_vs_bg.csv"  # adjust if needed
df_test = pd.read_csv(TEST_MANIFEST_PATH).reset_index(drop=True)

print("test rows:", len(df_test))
print("test label counts:\n", df_test["label"].value_counts())

# -------------------------
# Labels (MUST match train)
# -------------------------
# IMPORTANT: reuse label2id from training
# Example:
# label2id = {"background": 0, "goal": 1}

assert "goal" in label2id, "label2id must come from training"

# -------------------------
# Clip extraction
# -------------------------
def extract_clip_cv2(
    video_path,
    center_sec,
    clip_sec=4.0,
    num_frames=16,
    size=112,
):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise RuntimeError(f"Could not open video: {video_path}")

    fps = cap.get(cv2.CAP_PROP_FPS) or 25.0
    start_sec = max(0.0, float(center_sec) - clip_sec / 2)
    start_frame = int(start_sec * fps)

    frames = []
    step = int(max(1, (clip_sec * fps) / num_frames))

    for i in range(num_frames):
        cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame + i * step)
        ok, frame = cap.read()
        if not ok:
            break
        frame = cv2.resize(frame, (size, size), interpolation=cv2.INTER_AREA)
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        frames.append(frame)

    cap.release()

    if len(frames) == 0:
        raise RuntimeError(f"No frames read from: {video_path}")

    while len(frames) < num_frames:
        frames.append(frames[-1].copy())

    arr = np.stack(frames, axis=0).astype(np.float32) / 255.0
    arr = np.transpose(arr, (3, 0, 1, 2))  # (C,T,H,W)
    return torch.from_numpy(arr)

# -------------------------
# Dataset (TEST)
# -------------------------
class SoccerNetTestClipDataset(Dataset):
    def __init__(self, df, label2id, clip_sec=4.0, num_frames=16, size=112):
        self.df = df.reset_index(drop=True)
        self.label2id = label2id
        self.clip_sec = clip_sec
        self.num_frames = num_frames
        self.size = size

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        r = self.df.iloc[idx]
        x = extract_clip_cv2(
            r.video_path,
            r.center_sec,
            self.clip_sec,
            self.num_frames,
            self.size,
        )

        # labeled test
        if r.label in self.label2id:
            y = self.label2id[r.label]
        else:
            y = -1  # unlabeled test (inference-only)

        return x, torch.tensor(y, dtype=torch.long)

# -------------------------
# DataLoader (TEST)
# -------------------------
test_ds = SoccerNetTestClipDataset(
    df_test,
    label2id,
    clip_sec=4.0,
    num_frames=16,
    size=112,
)

test_loader = DataLoader(
    test_ds,
    batch_size=6,
    shuffle=False,
    num_workers=2,
    pin_memory=True,
)

print("test loader ready")

# CELL 8 — Model + optimizer + auto-resume from Drive
import torch
from torchvision.models.video import r2plus1d_18

device = "cuda" if torch.cuda.is_available() else "cpu"

model = r2plus1d_18(weights="DEFAULT")  # pretrained
model.fc = torch.nn.Linear(model.fc.in_features, num_classes)
model = model.to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
criterion = torch.nn.CrossEntropyLoss()

LATEST = f"{CKPT_DIR}/latest.pt"

def save_ckpt(path, model, optim, epoch, label2id):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    torch.save({
        "epoch": epoch,
        "model": model.state_dict(),
        "optim": optim.state_dict(),
        "label2id": label2id
    }, path)

def load_ckpt(path, model, optim=None, map_location="cpu"):
    ckpt = torch.load(path, map_location=map_location)
    model.load_state_dict(ckpt["model"])
    if optim is not None and "optim" in ckpt:
        optim.load_state_dict(ckpt["optim"])
    return ckpt.get("epoch", 0), ckpt.get("label2id", None)

start_epoch = 0
if os.path.exists(LATEST):
    start_epoch, saved_label2id = load_ckpt(LATEST, model, optimizer, map_location=device)
    print("Resumed from epoch:", start_epoch)
    # sanity: labels should match
    if saved_label2id is not None and saved_label2id != label2id:
        print("WARNING: label mapping differs from checkpoint. You should keep a stable manifest/labels.")
else:
    print("No checkpoint found, training from scratch.")

import os, pandas as pd

print("MANIFEST_PATH:", MANIFEST_PATH)
assert os.path.exists(MANIFEST_PATH), f"Manifest not found: {MANIFEST_PATH}"

df = pd.read_csv(MANIFEST_PATH)
print("Rows:", len(df))
print("Unique video files:", df["video_path"].nunique())
print(df[["split","label"]].value_counts().head(10))

import os, shutil
from tqdm import tqdm

df = pd.read_csv(MANIFEST_PATH)

LOCAL_VIDEO_ROOT = "/content/as_soccernet_local_videos"
os.makedirs(LOCAL_VIDEO_ROOT, exist_ok=True)

def to_local_path(src_path: str) -> str:
    prefix = "/content/drive/MyDrive/"
    if src_path.startswith(prefix):
        rel = src_path[len(prefix):]          # keep folder structure under MyDrive
    else:
        rel = src_path.lstrip("/").replace("/", "_")  # fallback: flatten
    return os.path.join(LOCAL_VIDEO_ROOT, rel)

src_paths = sorted(df["video_path"].unique().tolist())

copied = 0
for src in tqdm(src_paths, desc="Copying referenced videos to /content"):
    dst = to_local_path(src)
    os.makedirs(os.path.dirname(dst), exist_ok=True)

    if not os.path.exists(src):
        raise FileNotFoundError(f"Missing source video: {src}")

    # copy if missing or size differs
    if (not os.path.exists(dst)) or (os.path.getsize(dst) != os.path.getsize(src)):
        shutil.copy2(src, dst)
        copied += 1

print("Copied/updated video files:", copied)
print("Example mapping:")
print("  src:", src_paths[0])
print("  dst:", to_local_path(src_paths[0]))

import pandas as pd, os

df = pd.read_csv(MANIFEST_PATH)
df["video_path"] = df["video_path"].apply(to_local_path)

MANIFEST_LOCAL = f"{WORK_DIR}/manifest_local.csv"
df.to_csv(MANIFEST_LOCAL, index=False)

print("Wrote local manifest:", MANIFEST_LOCAL)
print("Example local path:", df["video_path"].iloc[0])

import cv2
import numpy as np
import torch
from torch.utils.data import Dataset, DataLoader
import pandas as pd

MANIFEST_PATH = MANIFEST_LOCAL  # <-- switch to local manifest

df_all = pd.read_csv(MANIFEST_PATH)
df_train = df_all[df_all["split"] == "train"].reset_index(drop=True)
df_valid = df_all[df_all["split"] == "valid"].reset_index(drop=True)

print("train rows:", len(df_train))
print("valid rows:", len(df_valid))

# labels from train only
labels = sorted(df_train["label"].unique().tolist())
label2id = {l:i for i,l in enumerate(labels)}
num_classes = len(labels)
print("labels:", labels)
print("num_classes:", num_classes)

def extract_clip_cv2(video_path, center_sec, clip_sec=4.0, num_frames=16, size=112):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise RuntimeError(f"Could not open video: {video_path}")

    fps = cap.get(cv2.CAP_PROP_FPS) or 25.0
    start_sec = max(0.0, center_sec - clip_sec/2)
    start_frame = int(start_sec * fps)

    frames = []
    step = int(max(1, (clip_sec * fps) / num_frames))

    for i in range(num_frames):
        cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame + i*step)
        ok, frame = cap.read()
        if not ok:
            break
        frame = cv2.resize(frame, (size, size), interpolation=cv2.INTER_AREA)
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        frames.append(frame)

    cap.release()

    if len(frames) == 0:
        raise RuntimeError(f"No frames read from: {video_path}")

    while len(frames) < num_frames:
        frames.append(frames[-1].copy())

    arr = np.stack(frames, axis=0).astype(np.float32) / 255.0  # (T,H,W,C)
    arr = np.transpose(arr, (3,0,1,2))  # (C,T,H,W)
    return torch.from_numpy(arr)

class SoccerNetClipDataset(Dataset):
    def __init__(self, df, label2id, clip_sec=4.0, num_frames=16, size=112):
        self.df = df.reset_index(drop=True)
        self.label2id = label2id
        self.clip_sec = clip_sec
        self.num_frames = num_frames
        self.size = size

    def __len__(self):
        return len(self.df)

    def __getitem__(self, idx):
        r = self.df.iloc[idx]
        x = extract_clip_cv2(r.video_path, r.center_sec, self.clip_sec, self.num_frames, self.size)
        y = self.label2id[r.label]
        return x, torch.tensor(y, dtype=torch.long)

train_ds = SoccerNetClipDataset(df_train, label2id, clip_sec=4.0, num_frames=16, size=112)
val_ds   = SoccerNetClipDataset(df_valid, label2id, clip_sec=4.0, num_frames=16, size=112)

# For local disk, 2 workers is usually good; try 4 later if stable
train_loader = DataLoader(train_ds, batch_size=16, shuffle=True, num_workers=2, pin_memory=True)
val_loader   = DataLoader(val_ds, batch_size=16, shuffle=False, num_workers=2, pin_memory=True)

print("Loaders ready.")

import torch, os
from torchvision.models.video import r2plus1d_18

device = "cuda" if torch.cuda.is_available() else "cpu"
print("device:", device)

model = r2plus1d_18(weights="DEFAULT")
model.fc = torch.nn.Linear(model.fc.in_features, num_classes)
model = model.to(device)

optimizer = torch.optim.Adam(model.parameters(), lr=1e-4)
criterion = torch.nn.CrossEntropyLoss()

LATEST = f"{CKPT_DIR}/latest.pt"
BEST   = f"{CKPT_DIR}/best.pt"

def load_ckpt(path, model, optim=None, map_location="cpu"):
    ckpt = torch.load(path, map_location=map_location)
    model.load_state_dict(ckpt["model"])
    if optim is not None and "optim" in ckpt:
        optim.load_state_dict(ckpt["optim"])
    return ckpt.get("epoch", 0), ckpt.get("label2id", None)

start_epoch = 0
resume_path = BEST if os.path.exists(BEST) else (LATEST if os.path.exists(LATEST) else None)

if resume_path:
    start_epoch, saved_label2id = load_ckpt(resume_path, model, optimizer, map_location=device)
    print("Resumed from:", resume_path, "epoch:", start_epoch)
    if saved_label2id is not None and saved_label2id != label2id:
        print("WARNING: label2id mismatch vs checkpoint (check manifest/labels).")
else:
    print("No checkpoint found, training from scratch.")

print("Model device check:", next(model.parameters()).device)

from tqdm import tqdm
import torch
from torch.cuda.amp import autocast, GradScaler

EPOCHS = 10  # set what you want now

scaler = GradScaler()

best_val = -1.0
BEST = f"{CKPT_DIR}/best.pt"
LATEST = f"{CKPT_DIR}/latest.pt"

def save_ckpt(path, model, optim, epoch, label2id):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    torch.save({
        "epoch": epoch,
        "model": model.state_dict(),
        "optim": optim.state_dict(),
        "label2id": label2id
    }, path)

for epoch in range(start_epoch, start_epoch + EPOCHS):
    # ---- train ----
    model.train()
    running = 0.0
    pbar = tqdm(train_loader, desc=f"Epoch {epoch+1} [train]")
    for x, y in pbar:
        x = x.to(device, non_blocking=True)
        y = y.to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)
        with autocast():
            logits = model(x)
            loss = criterion(logits, y)

        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()

        running += loss.item()
        pbar.set_postfix(train_loss=running / (pbar.n + 1))

    # ---- validate ----
    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for x, y in val_loader:
            x = x.to(device, non_blocking=True)
            y = y.to(device, non_blocking=True)
            logits = model(x)
            preds = logits.argmax(dim=1)
            correct += (preds == y).sum().item()
            total += y.size(0)

    val_acc = correct / max(total, 1)
    print(f"Epoch {epoch+1} | val acc: {val_acc:.4f}")

    # ---- save latest ----
    save_ckpt(LATEST, model, optimizer, epoch + 1, label2id)

    # ---- save best ----
    if val_acc > best_val:
        best_val = val_acc
        save_ckpt(BEST, model, optimizer, epoch + 1, label2id)
        print("Saved BEST:", BEST, "val:", best_val)

print("Training done.")

import torch
import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics import (
    precision_recall_fscore_support,
    confusion_matrix,
    ConfusionMatrixDisplay,
    precision_recall_curve,
    average_precision_score,
    roc_curve,
    auc,
)

device = "cuda" if torch.cuda.is_available() else "cpu"

# ---- Load BEST checkpoint ----
BEST = f"{CKPT_DIR}/best.pt"
ckpt = torch.load(BEST, map_location=device)
model.load_state_dict(ckpt["model"])
model.to(device)
model.eval()

# ---- Identify goal class index ----
assert "goal" in label2id, "Label 'goal' not found in label2id"
goal_id = label2id["goal"]

# ---- Collect labels, hard preds, and goal probabilities ----
y_true = []
y_pred = []
y_score = []  # P(goal)

with torch.no_grad():
    for x, y in val_loader:
        x = x.to(device, non_blocking=True)
        logits = model(x)  # [B, C]

        probs = torch.softmax(logits, dim=1)         # [B, C]
        goal_prob = probs[:, goal_id].cpu().numpy()  # [B]

        preds = logits.argmax(dim=1).cpu().numpy()

        y_true.extend(y.numpy())
        y_pred.extend(preds)
        y_score.extend(goal_prob)

y_true = np.array(y_true)
y_pred = np.array(y_pred)
y_score = np.array(y_score)

# ---- Binary: goal vs not-goal ----
y_true_bin = (y_true == goal_id).astype(int)
y_pred_bin = (y_pred == goal_id).astype(int)

prec, rec, f1, _ = precision_recall_fscore_support(
    y_true_bin, y_pred_bin, average="binary", zero_division=0
)
cm = confusion_matrix(y_true_bin, y_pred_bin)

print("Goal metrics (validation):")
print(f"  Precision: {prec:.4f}")
print(f"  Recall   : {rec:.4f}")
print(f"  F1-score : {f1:.4f}")

# =========================
#          CHARTS
# =========================

# 1) Confusion matrix heatmap
fig, ax = plt.subplots(figsize=(5, 5))
disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=["background", "goal"])
disp.plot(ax=ax, values_format="d", cmap="Blues", colorbar=False)
ax.set_title("Confusion Matrix (Goal vs Background)")
plt.tight_layout()
plt.show()

# 2) Score distributions (P(goal)) for each true class
fig, ax = plt.subplots(figsize=(7, 4))
ax.hist(y_score[y_true_bin == 0], bins=40, alpha=0.6, label="True background")
ax.hist(y_score[y_true_bin == 1], bins=40, alpha=0.6, label="True goal")
ax.set_title("Predicted Probability for Goal (Validation)")
ax.set_xlabel("P(goal)")
ax.set_ylabel("Count")
ax.legend()
plt.tight_layout()
plt.show()

# 3) Precision–Recall curve (+ Average Precision)
pr_prec, pr_rec, pr_thresh = precision_recall_curve(y_true_bin, y_score)
ap = average_precision_score(y_true_bin, y_score)

fig, ax = plt.subplots(figsize=(6, 5))
ax.plot(pr_rec, pr_prec)
ax.set_title(f"Precision–Recall Curve (AP={ap:.4f})")
ax.set_xlabel("Recall")
ax.set_ylabel("Precision")
ax.set_xlim(0, 1)
ax.set_ylim(0, 1)
plt.tight_layout()
plt.show()

# 4) ROC curve (+ AUC) (optional but handy)
fpr, tpr, _ = roc_curve(y_true_bin, y_score)
roc_auc = auc(fpr, tpr)

fig, ax = plt.subplots(figsize=(6, 5))
ax.plot(fpr, tpr)
ax.plot([0, 1], [0, 1], linestyle="--")
ax.set_title(f"ROC Curve (AUC={roc_auc:.4f})")
ax.set_xlabel("False Positive Rate")
ax.set_ylabel("True Positive Rate")
ax.set_xlim(0, 1)
ax.set_ylim(0, 1)
plt.tight_layout()
plt.show()

# CELL — Evaluation on TEST split only

import torch
import numpy as np
import matplotlib.pyplot as plt

from sklearn.metrics import (
    confusion_matrix,
    ConfusionMatrixDisplay,
    precision_recall_fscore_support,
    precision_recall_curve,
    average_precision_score,
    roc_curve,
    auc,
)

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device)
model.eval()

goal_id = label2id["goal"]

y_true = []
y_pred = []
y_score = []   # P(goal)

with torch.no_grad():
    for x, y in test_loader:
        x = x.to(device, non_blocking=True)

        logits = model(x)
        probs = torch.softmax(logits, dim=1)
        p_goal = probs[:, goal_id].detach().cpu().numpy()

        preds = logits.argmax(dim=1).detach().cpu().numpy()

        y_score.extend(p_goal)
        y_pred.extend(preds)
        y_true.extend(y.numpy())

y_true = np.array(y_true)
y_pred = np.array(y_pred)
y_score = np.array(y_score)

# -------------------------
# Detect labeled vs unlabeled test
# -------------------------
is_labeled = np.any(y_true >= 0)

print("Test samples:", len(y_score))
print("Labeled test:", is_labeled)

# =========================
# Metrics (ONLY if labeled)
# =========================
if is_labeled:
    y_true_bin = (y_true == goal_id).astype(int)
    y_pred_bin = (y_pred == goal_id).astype(int)

    prec, rec, f1, _ = precision_recall_fscore_support(
        y_true_bin, y_pred_bin, average="binary", zero_division=0
    )

    print("\nTEST metrics (goal vs background):")
    print(f"  Precision: {prec:.4f}")
    print(f"  Recall   : {rec:.4f}")
    print(f"  F1-score : {f1:.4f}")

    # Confusion matrix
    cm = confusion_matrix(y_true_bin, y_pred_bin)
    fig, ax = plt.subplots(figsize=(5, 5))
    ConfusionMatrixDisplay(cm, display_labels=["background", "goal"]).plot(
        ax=ax, cmap="Blues", values_format="d", colorbar=False
    )
    ax.set_title("Confusion Matrix (TEST)")
    plt.tight_layout()
    plt.show()

    # Precision–Recall curve
    p, r, _ = precision_recall_curve(y_true_bin, y_score)
    ap = average_precision_score(y_true_bin, y_score)

    fig, ax = plt.subplots(figsize=(6, 5))
    ax.plot(r, p)
    ax.set_title(f"Precision–Recall (TEST)  AP={ap:.4f}")
    ax.set_xlabel("Recall")
    ax.set_ylabel("Precision")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    plt.tight_layout()
    plt.show()

    # ROC curve
    fpr, tpr, _ = roc_curve(y_true_bin, y_score)
    roc_auc = auc(fpr, tpr)

    fig, ax = plt.subplots(figsize=(6, 5))
    ax.plot(fpr, tpr)
    ax.plot([0, 1], [0, 1], linestyle="--")
    ax.set_title(f"ROC (TEST)  AUC={roc_auc:.4f}")
    ax.set_xlabel("FPR")
    ax.set_ylabel("TPR")
    ax.set_xlim(0, 1)
    ax.set_ylim(0, 1)
    plt.tight_layout()
    plt.show()

# =========================
# Always-valid plots
# =========================

# Probability histogram (works even if unlabeled)
fig, ax = plt.subplots(figsize=(7, 4))
ax.hist(y_score, bins=40, alpha=0.8)
ax.set_title("Predicted P(goal) Distribution (TEST)")
ax.set_xlabel("P(goal)")
ax.set_ylabel("Count")
plt.tight_layout()
plt.show()

# CELL 9 — Train (saves each epoch to Drive)
from tqdm import tqdm
import torch

EPOCHS = 20

best_val = -1.0
BEST = f"{CKPT_DIR}/best.pt"

for epoch in range(start_epoch, start_epoch + EPOCHS):
    # ---- train ----
    model.train()
    running = 0.0
    pbar = tqdm(train_loader, desc=f"Epoch {epoch+1} [train]")
    for x, y in pbar:
        x = x.to(device, non_blocking=True)
        y = y.to(device, non_blocking=True)

        optimizer.zero_grad(set_to_none=True)
        logits = model(x)
        loss = criterion(logits, y)
        loss.backward()
        optimizer.step()

        running += loss.item()
        pbar.set_postfix(train_loss=running / (pbar.n + 1))

    # ---- validate ----
    model.eval()
    correct, total = 0, 0
    with torch.no_grad():
        for x, y in val_loader:
            x = x.to(device, non_blocking=True)
            y = y.to(device, non_blocking=True)
            logits = model(x)
            preds = logits.argmax(dim=1)
            correct += (preds == y).sum().item()
            total += y.size(0)

    val_acc = correct / max(total, 1)
    print(f"Epoch {epoch+1} | val acc: {val_acc:.4f}")

    # ---- save latest ----
    save_ckpt(LATEST, model, optimizer, epoch + 1, label2id)

    # ---- save best ----
    if val_acc > best_val:
        best_val = val_acc
        save_ckpt(BEST, model, optimizer, epoch + 1, label2id)
        print("Saved BEST:", BEST, "val:", best_val)

# CELL — Sliding-window goal spotting (1s stride) on a RANDOM validation half (mkv)

import cv2
import numpy as np
import torch
import matplotlib.pyplot as plt
import pandas as pd
import random

device = "cuda" if torch.cuda.is_available() else "cpu"
model.to(device).eval()

assert "goal" in label2id, "Label 'goal' not in label2id"
goal_id = label2id["goal"]

# -------------------------
# Pick a random validation half (video_path) from df_valid
# -------------------------
assert "df_valid" in globals(), "df_valid not found. Make sure you've created df_valid from your manifest."
assert "video_path" in df_valid.columns, "df_valid must contain a 'video_path' column."

SEED = 42
random.seed(SEED)

valid_paths = df_valid["video_path"].dropna().unique().tolist()
valid_paths = [p for p in valid_paths if isinstance(p, str) and len(p) > 0]

if len(valid_paths) == 0:
    raise RuntimeError("No valid video paths found in df_valid.")

VIDEO_PATH = random.choice(valid_paths)
print("Random validation half:", VIDEO_PATH)

# Optional: print which game/half it came from (if columns exist)
cols = [c for c in ["rel_game", "half"] if c in df_valid.columns]
if cols:
    ex = df_valid[df_valid["video_path"] == VIDEO_PATH].iloc[0]
    print("Meta:", {c: ex[c] for c in cols})

# -------------------------
# Helpers
# -------------------------
def video_duration_fps(video_path: str):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise RuntimeError(f"Could not open video: {video_path}")
    fps = cap.get(cv2.CAP_PROP_FPS) or 25.0
    n = cap.get(cv2.CAP_PROP_FRAME_COUNT) or 0
    cap.release()
    if n <= 1:
        raise RuntimeError(f"Could not read frame count for: {video_path}")
    return float(n / fps), float(fps)

def extract_clip_cv2(video_path, center_sec, clip_sec=4.0, num_frames=16, size=112):
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        raise RuntimeError(f"Could not open video: {video_path}")

    fps = cap.get(cv2.CAP_PROP_FPS) or 25.0
    start_sec = max(0.0, float(center_sec) - clip_sec / 2)
    start_frame = int(start_sec * fps)

    frames = []
    step = int(max(1, (clip_sec * fps) / num_frames))

    for i in range(num_frames):
        cap.set(cv2.CAP_PROP_POS_FRAMES, start_frame + i * step)
        ok, frame = cap.read()
        if not ok:
            break
        frame = cv2.resize(frame, (size, size), interpolation=cv2.INTER_AREA)
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        frames.append(frame)

    cap.release()

    if len(frames) == 0:
        raise RuntimeError(f"No frames read from: {video_path}")

    while len(frames) < num_frames:
        frames.append(frames[-1].copy())

    arr = np.stack(frames, axis=0).astype(np.float32) / 255.0  # (T,H,W,C)
    arr = np.transpose(arr, (3, 0, 1, 2))  # (C,T,H,W)
    return torch.from_numpy(arr)

def nms_1d(times, scores, min_separation_sec=8.0):
    """Greedy NMS on 1D timestamps: keep highest score, suppress within +/- min_separation_sec/2."""
    if len(times) == 0:
        return np.array([]), np.array([])
    order = np.argsort(scores)[::-1]
    keep = []
    suppressed = np.zeros(len(times), dtype=bool)
    half = min_separation_sec / 2.0

    for i in order:
        if suppressed[i]:
            continue
        keep.append(i)
        close = np.abs(times - times[i]) <= half
        suppressed |= close
        suppressed[i] = False

    keep = np.array(keep, dtype=int)
    korder = np.argsort(times[keep])
    return times[keep][korder], scores[keep][korder]

def spot_goals_sliding_window(
    video_path,
    clip_sec=4.0,
    stride_sec=1.0,
    num_frames=16,
    size=112,
    threshold=0.998,
    nms_sep_sec=20.0,
    max_seconds=1200,   # set None to scan full 45min; 300 is a fast sanity run
):
    dur, _ = video_duration_fps(video_path)
    end_time = dur if max_seconds is None else min(dur, float(max_seconds))

    t0 = clip_sec / 2.0
    t1 = end_time - clip_sec / 2.0
    if t1 <= t0:
        raise RuntimeError("Video too short for chosen clip_sec/max_seconds.")

    centers = np.arange(t0, t1 + 1e-9, stride_sec, dtype=np.float32)

    probs = []
    with torch.no_grad():
        for c in centers:
            x = extract_clip_cv2(video_path, c, clip_sec=clip_sec, num_frames=num_frames, size=size)
            x = x.unsqueeze(0).to(device)  # [1,C,T,H,W]
            logits = model(x)
            probs.append(torch.softmax(logits, dim=1)[0, goal_id].item())

    probs = np.array(probs, dtype=np.float32)

    det_mask = probs >= threshold
    det_times = centers[det_mask]
    det_scores = probs[det_mask]

    final_times, final_scores = nms_1d(det_times, det_scores, min_separation_sec=nms_sep_sec)
    return centers, probs, final_times, final_scores

# -------------------------
# Run spotting
# -------------------------
centers, p_goal, pred_times, pred_scores = spot_goals_sliding_window(
    VIDEO_PATH,
    clip_sec=4.0,
    stride_sec=1.0,
    num_frames=16,
    size=112,
    threshold=0.998,
    nms_sep_sec=20.0,
    max_seconds=None,   # change to None for full half
)

print(f"\nWindows evaluated: {len(centers)}")
print("Predicted goal timestamps (sec):")
for t, s in zip(pred_times, pred_scores):
    print(f"  t={t:7.2f}s   P(goal)={s:.3f}")

# Plot signal + detections
fig, ax = plt.subplots(figsize=(14, 3))
ax.plot(centers, p_goal)
if len(pred_times) > 0:
    ax.scatter(pred_times, pred_scores, marker="x", label="Predicted goals (after NMS)")
ax.set_title("Sliding-window goal spotting on random validation half (1s stride)")
ax.set_xlabel("Time (s)")
ax.set_ylabel("P(goal)")
ax.set_ylim(0, 1)
ax.legend()
plt.tight_layout()
plt.show()